### ISSUE TITLE
Read Me ergänzen - Doku erweitern

### ISSUE THREAD

**Issue by ludwich66** [volkerschulz/NIU-API#1]
Hallo Volker,
kannst du die theoretisch vorhandene Felder mit in die Readme aufnehmen?
Bei mir ist nur ein kleiner Teil der Daten vorhanden - (km, Ladestand , Nutzungstage)
Der "lockStatus" ist in der Nie App "verschlossen", hier finde ich keinen Wert dazu -??

This vehicle
sn, specialEdition, vehicleColorImg, vehicleLogoImg, vehicleTypeId, indexHeaderBg, scootorImg, batteryInfoBg, myPageHeaderBg, listScooterImg, name, frameNo, engineNo, isSelected, isMaster, bindNum, renovated, bindDate, isShow, isLite, gpsTimestamp, infoTimestamp, productType, process, brand, isDoubleBattery, features, type
 
motor info
isCharging, lockStatus, isAccOn, isFortificationOn, isConnected, postion, hdop, time, batteries, leftTime, estimatedMileage, gpsTimestamp, infoTimestamp, nowSpeed, batteryDetail, centreCtrlBattery, ss_protocol_ver, ss_online_sta, gps, gsm, lastTrack
 
overall tally
bindDaysCount, totalMileage
 
battery info
batteries, isCharging, centreCtrlBattery, batteryDetail, estimatedMileage
 
battery health
batteries, isDoubleBattery
 
Tracks
?? (Gps-Koordinaten)

Danke Schöne Grüße 
ludwich

**Comment by BlueAndi** [comment]
Du kannst sie auch hier entnehmen: https://github.com/BlueAndi/niu-cloud-connector/blob/master/doc/API.md

Oder aus der HTML Doku: https://github.com/BlueAndi/niu-cloud-connector/blob/master/doc/html

**Comment by ludwich66** [comment]
Danke Dir

Da war Andi schneller ;-)

ludwich


Die HDOP ist ein Faktor, der die relative Genauigkeit einer horizontalen Position bestimmt. Je kleiner der DOP-Wert, desto besser die Geometrie.

**Comment by BlueAndi** [comment]
Habe HDOP ergänzt, danke.

Ich glaube übrigens das Volker von den Issues hier gar nichts mitbekommt, da er sich wohl aus der Watch Liste ausgetragen hat.

**Comment by ludwich66** [comment]
Gern, da kommt ja jetzt eine Menge zusammen, da läßt sich sicher etwas basteln.
Die Smart Home Liga hat sich ja auch schon gemeldet - mal schauen ob ich auch was hinbekomme.
Weis jemand nach welchen Regeln die GPS Daten übertragen werden?
Auf Abruf und wie im Fahrbetrieb nach Zeit alle X Meter?
Ich habe leider keine Tracks bei mir im Roller?

Servus
ludwich

**Comment by BlueAndi** [comment]
Sag mal ludwich, kannst Du hier mehr lesen als ich sehen kann? ;-)
Das entnehme ich Deiner Antwort ... irgendwie!?

PS: Bei den Track Items scheint es nicht nach Zeit zu gehen, sondern nach gefahrener Distanz.

**Comment by ludwich66** [comment]
Ich habe auch das Elektroroller Forum und die GitHubseiten gelesen ;-)
Das ist eine Verknüpfung ;-)

ludwich
